"""Done

Revision ID: 68f2ca5dc0df
Revises: e03db728ce4e
Create Date: 2025-03-16 19:12:13.513100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f2ca5dc0df'
down_revision = 'e03db728ce4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
