"""Add missing created_at column

Revision ID: 7de240c8f3f1
Revises: 9f9b599a9728
Create Date: 2025-03-17 01:53:08.093820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de240c8f3f1'
down_revision = '9f9b599a9728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'timestamp')
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.VARCHAR(length=255), nullable=False))
    op.add_column('messages', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(length=100), nullable=False))
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
