"""Initial migration

Revision ID: 9f9b599a9728
Revises: 68f2ca5dc0df
Create Date: 2025-03-16 22:53:31.478259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9b599a9728'
down_revision = '68f2ca5dc0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('username', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(length=100), nullable=False))
    op.add_column('messages', sa.Column('content', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
